import { Web3ModalProvider } from 'libs/web3Modal';
import 'libs/styles/global.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Web3ModalProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Web3ModalProvider>
  );
}
